# Generated by Django 4.2.5 on 2023-10-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanemisan', '0002_things_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='things',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='things',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
